//
//  main.swift
//  CineFlowPackage
//
//  Created by sanlorng char on 2025/9/27.
//

import ArgumentParser
import Foundation

struct SecretGenerator: ParsableCommand {
    @Argument(help: "The path to the input .env file.")
    var inputFile: String

    @Argument(help: "The path to the output Secret.swift file.")
    var outputFile: String

    func run() {
        let inputURL = URL(fileURLWithPath: inputFile)
        let outputURL = URL(fileURLWithPath: outputFile)
        let fileManager = FileManager.default

        do {
            try fileManager.createDirectory(
                at: outputURL.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )

            guard fileManager.fileExists(atPath: inputURL.path()) else {
                try writeFallbackOutput(
                    to: outputURL,
                    warning: "warning: .env file not found at \(inputFile). Generated an empty Secrets.swift."
                )
                return
            }

            let envContent = try String(contentsOf: inputURL, encoding: .utf8)
            let swiftCode = generateSwiftCode(from: envContent)
            try swiftCode.write(to: outputURL, atomically: true, encoding: .utf8)

            print("Successfully generated Secrets.swift at \(outputFile)")
        } catch {
            do {
                try writeFallbackOutput(
                    to: outputURL,
                    warning: "warning: failed to generate Secrets.swift: \(error). Generated an empty fallback instead."
                )
            } catch {
                print("error: failed to write fallback Secrets.swift: \(error)")
                Foundation.exit(1)
            }
        }
    }

    private func generateSwiftCode(from envContent: String) -> String {
        var swiftCode = """
            // This file is generated by a build plugin. Do not edit.
            import Foundation

            enum Secrets {

            """

        let lines = envContent.split(whereSeparator: \.isNewline)
        for line in lines {
            let trimmedLine = line.trimmingCharacters(in: .whitespaces)
            if trimmedLine.isEmpty || trimmedLine.hasPrefix("#") {
                continue
            }

            guard let separatorIndex = trimmedLine.firstIndex(of: "=") else {
                continue
            }

            let key = trimmedLine[..<separatorIndex].trimmingCharacters(in: .whitespaces)
            let value = trimmedLine[trimmedLine.index(after: separatorIndex)...].trimmingCharacters(in: .whitespaces)
            let swiftKey = sanitizedSwiftIdentifier(from: toCamelCase(String(key)))
            let escapedValue = escapeSwiftStringLiteral(String(value))

            guard !swiftKey.isEmpty else {
                continue
            }

            swiftCode += "    static let \(swiftKey) = \"\(escapedValue)\"\n"
        }

        swiftCode += "}\n"
        return swiftCode
    }

    private func writeFallbackOutput(to outputURL: URL, warning: String) throws {
        let fallback = """
            // This file is generated by a build plugin. Do not edit.
            import Foundation

            enum Secrets {}
            """

        try fallback.write(to: outputURL, atomically: true, encoding: .utf8)
        print(warning)
    }

    private func toCamelCase(_ string: String) -> String {
        string.lowercased()
            .split(separator: "_")
            .enumerated()
            .map { index, part in
                index == 0 ? String(part) : String(part).capitalized
            }
            .joined()
    }

    private func sanitizedSwiftIdentifier(from string: String) -> String {
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "_"))
        let filteredScalars = string.unicodeScalars.map { scalar in
            allowed.contains(scalar) ? Character(scalar) : "_"
        }
        var identifier = String(filteredScalars)

        if let first = identifier.first, first.isNumber {
            identifier = "_" + identifier
        }

        return identifier
    }

    private func escapeSwiftStringLiteral(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}

SecretGenerator.main()
