#!/usr/bin/env python3

from __future__ import annotations

import pathlib
import re
import sys


def to_camel_case(key: str) -> str:
    parts = [part for part in key.lower().split("_") if part]
    if not parts:
        return ""
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


def sanitize_identifier(identifier: str) -> str:
    sanitized = re.sub(r"[^0-9A-Za-z_]", "_", identifier)
    if sanitized[:1].isdigit():
        sanitized = "_" + sanitized
    return sanitized


def escape_swift_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace("\"", "\\\"")


def parse_env_file(input_path: pathlib.Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not input_path.exists():
        return values

    for raw_line in input_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        raw_key, raw_value = line.split("=", 1)
        swift_key = sanitize_identifier(to_camel_case(raw_key.strip()))
        if not swift_key:
            continue

        values[swift_key] = raw_value.strip()

    return values


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate-secrets.py <input> <output>", file=sys.stderr)
        return 1

    input_path = pathlib.Path(sys.argv[1])
    output_path = pathlib.Path(sys.argv[2])
    output_path.parent.mkdir(parents=True, exist_ok=True)

    values = parse_env_file(input_path)
    values.setdefault("dandanAppId", "")
    values.setdefault("dandanAppSecret", "")

    lines = [
        "// This file is generated by a build plugin. Do not edit.",
        "import Foundation",
        "",
        "enum Secrets {",
    ]

    for key in sorted(values):
        lines.append(f'    static let {key} = "{escape_swift_string(values[key])}"')

    lines.append("}")
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
