#!/bin/bash

set -euo pipefail

INPUT_FILE="${1:?input file path is required}"
OUTPUT_FILE="${2:?output file path is required}"
OUTPUT_DIR="$(dirname "$OUTPUT_FILE")"

mkdir -p "$OUTPUT_DIR"

cat > "$OUTPUT_FILE" <<'EOF'
// This file is generated by a build plugin. Do not edit.
import Foundation

enum Secrets {
EOF

has_dandan_app_id=0
has_dandan_app_secret=0

if [[ -f "$INPUT_FILE" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"
    trimmed="${trimmed%"${trimmed##*[![:space:]]}"}"

    if [[ -z "$trimmed" || "${trimmed:0:1}" == "#" ]]; then
      continue
    fi

    if [[ "$trimmed" != *=* ]]; then
      continue
    fi

    key="${trimmed%%=*}"
    value="${trimmed#*=}"

    key="${key#"${key%%[![:space:]]*}"}"
    key="${key%"${key##*[![:space:]]}"}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"

    lower_key="$(printf '%s' "$key" | tr '[:upper:]' '[:lower:]')"
    camel_key="$(printf '%s' "$lower_key" | awk -F'_' '{
      out = $1
      for (i = 2; i <= NF; i++) {
        if (length($i) > 0) {
          out = out toupper(substr($i, 1, 1)) substr($i, 2)
        }
      }
      print out
    }')"
    swift_key="$(printf '%s' "$camel_key" | sed 's/[^[:alnum:]_]/_/g')"

    if [[ "$swift_key" =~ ^[0-9] ]]; then
      swift_key="_${swift_key}"
    fi

    escaped_value="${value//\\/\\\\}"
    escaped_value="${escaped_value//\"/\\\"}"

    if [[ -n "$swift_key" ]]; then
      if [[ "$swift_key" == "dandanAppId" ]]; then
        has_dandan_app_id=1
      fi

      if [[ "$swift_key" == "dandanAppSecret" ]]; then
        has_dandan_app_secret=1
      fi

      printf '    static let %s = "%s"\n' "$swift_key" "$escaped_value" >> "$OUTPUT_FILE"
    fi
  done < "$INPUT_FILE"
fi

if [[ "$has_dandan_app_id" -eq 0 ]]; then
  printf '    static let dandanAppId = ""\n' >> "$OUTPUT_FILE"
fi

if [[ "$has_dandan_app_secret" -eq 0 ]]; then
  printf '    static let dandanAppSecret = ""\n' >> "$OUTPUT_FILE"
fi

printf '}\n' >> "$OUTPUT_FILE"
